import React from 'react'
import PropTypes from 'prop-types'
import { Switch, Redirect, NavLink } from 'react-router-dom'
import { Helmet } from 'react-helmet'
import { connect } from 'react-redux'
import { router, NestedRoute, StatusRoute } from './router'
import { setClientLoad } from '@store/actions/actions'
// import './assets/style/style.scss'
// import './App.scss'